#!/bin/sh
#run by cron
logrotate -f /etc/logrotate_clamscan.conf


while read dir; 
do 
    [ -z "$dir" ] && continue
    nice -20 ionice -c3 clamscan -r -i --stdout $dir >> /var/log/clamav/clamscan.log
done < /etc/clamav/clamscan.conf
exit 0

