#!/bin/sh
#run by cron
logrotate -f /etc/logrotate_clamscan.conf
LOGFILE="/var/log/clamav/clamscan.log"

while read dir; 
do 
    [ -z "$dir" ] && continue
    echo "Dir: $dir" >> $LOGFILE
    nice -20 ionice -c3 clamscan -r -i --stdout $dir >> $LOGFILE  2>&1
done < /etc/clamav/clamscan.conf
exit 0

