Document: nagios-check-clamscan
Title: Debian nagios-check-clamscan Manual
Author: <insert document author here>
Abstract: This manual describes what nagios-check-clamscan is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nagios-check-clamscan/nagios-check-clamscan.sgml.gz

Format: postscript
Files: /usr/share/doc/nagios-check-clamscan/nagios-check-clamscan.ps.gz

Format: text
Files: /usr/share/doc/nagios-check-clamscan/nagios-check-clamscan.text.gz

Format: HTML
Index: /usr/share/doc/nagios-check-clamscan/html/index.html
Files: /usr/share/doc/nagios-check-clamscan/html/*.html
